// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTemperatureChange();
void onLedStateChange();

float temperature;
bool led_state;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READWRITE, 30 * SECONDS, onTemperatureChange);
  ArduinoCloud.addProperty(led_state, READWRITE, ON_CHANGE, onLedStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
